name: sn_thumbnail
version: 1.0.7+1
publish_to: none
description: A social media thumbnail post.
environment:
  sdk: ^3.6.0

dependencies:
  bitsdojo_window: ^0.1.6
  clipboard: ^0.1.3
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  gap: ^3.0.1
  get: 5.0.0-release-candidate-9.2.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  http: ^1.2.2
  iconify_flutter: ^0.0.7
  image_gallery_saver_plus: ^3.0.5
  image_picker: ^1.1.2
  image_scaler: ^0.0.2
  package_info_plus: ^8.0.2
  palette_generator: ^0.3.3+5
  path_provider: ^2.1.4
  screenshot: ^3.0.0
  shared_preferences: ^2.3.3
  uuid: ^4.5.0

dev_dependencies:
  build_runner: any
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.0
  # isar_generator:
  #   hosted: https://pub.isar-community.dev
  #   version: 3.1.7
  msix: ^3.16.8

flutter:
  uses-material-design: true

  assets:
    - "assets/icons/"

msix_config:
  display_name: SNThumbnail
  logo_path: assets\icons\launcher.png
  msix_version: 1.0.5.0
  install_certificate: false
