name: build release app

on:
  push:
    tags:
      - "v*"

jobs:

  # windows
  build-release-windows:
    runs-on: windows-latest

  # linux
  build-release-linux:
    runs-on: ubuntu-latest

  # macos
  build-release-macos:
    runs-on: macos-latest

  # android
  build-release-android:
    runs-on: android-latest
  
  # ios
  build-release-ios:
    runs-on: ios-latest

